### ISSUE TITLE
i cann't execute

### ISSUE THREAD

**Issue by waliguder** [decred/decred-php-api#6]
Fatal error: Maximum execution time of 30 seconds exceeded in E:\zt_6.27\apache24\htdocs\decred\vendor\mdanter\ecc\src\Primitives\CurveFp.php on line 148

**Comment by WellingtonBraga** [comment]
Hi, 

Could you please provide more information about what you were trying to do
when this error has occurred?

**Comment by WellingtonBraga** [comment]
Hi, 

Could you please provide more information about this error? What steps you took until got this message? Have you tried to use some examples?

Best Regards,
Wellington Braga

**Comment by dajohi** [comment]
@waliguder please reopen if still an issue.
