### ISSUE TITLE
Not getting same results as test cases

### ISSUE THREAD

**Issue by AgileCash** [decred/decred-php-api#8]
Any idea why I'm not getting the same results as the test cases for: 
`$result = \Decred\Crypto\Hash::blake("\x60");
echo $result;`

produces "cf6460f7a71af405ac8d12bba61ad8a2fc59821e7ee5d9fd1f0dfe245b88b980"

**Comment by R3VoLuT1OneR** [comment]
@AgileCash Which PHP version? can you share the `phpinfo` please.

**Comment by dajohi** [comment]
@AgileCash Please reopen if still an issue.
